apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: images
  labels:
    app: images
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
      - name: images
        image: trisberg/images:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1.0
            memory: 1024Mi
          requests:
            cpu: 0.5
            memory: 640Mi
        livenessProbe:
          httpGet:
            path: /application/status
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /application/status
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
        env:
        - name: SERVER_PORT
          value: '80'
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-root-password
        volumeMounts:
        - name: application-config
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: application-config
        configMap:
          name: images
          items:
          - key: application.yaml
            path: application.yaml
